#!/usr/bin/env bash
rm -rf dist
mkdir -p dist
echo "build src/ldlz.ls -> dist/ldlz.js ..."
./node_modules/.bin/lsc -cbp src/ldlz.ls > dist/ldlz.js
echo "build src/ldlz.styl -> dist/ldlz.css ..."
./node_modules/.bin/stylus -p src/ldlz.styl > dist/ldlz.css
echo "minifying ldlz.js ..."
./node_modules/.bin/uglifyjs dist/ldlz.js > dist/ldlz.min.js
echo "minifying ldlz.css ..."
./node_modules/.bin/uglifycss dist/ldlz.css > dist/ldlz.min.css
echo "copy pug file to dist/ ..."
cp src/ldlz.pug dist/ldlz.pug
echo "deploy into local web ..."
rm -rf web/static/assets/lib/ldlazy/dev/
mkdir -p web/static/assets/lib/ldlazy/dev/
cp -R dist/* web/static/assets/lib/ldlazy/dev/
echo "done."

